// XHawk lifecycle hooks for OpenCode
// Auto-generated by xhawk (xh init)
// Do not edit manually — changes will be overwritten on the next xh init.

export const XHHooksPlugin = async ({ $, directory }) => {
  const seenMessages = new Set()
  let currentSessionId = null

  return {
    event: async ({ event }) => {
      switch (event.type) {
        case "message.updated": {
          const msg = event.properties?.info
          if (!msg || msg.role !== "user") break
          if (seenMessages.has(msg.id)) break
          seenMessages.add(msg.id)

          if (msg.sessionID) currentSessionId = msg.sessionID

          const payload = JSON.stringify({
            session_id: currentSessionId || msg.sessionID || "",
            cwd: directory || process.cwd(),
          })
          try {
            await $`/opt/homebrew/bin/xh _memory-hook prompt-submit ${payload} --agent opencode`
          } catch {}
          break
        }
        case "session.idle": {
          if (!currentSessionId && event.properties?.sessionID) {
            currentSessionId = event.properties.sessionID
          }
          const payload = JSON.stringify({
            session_id: currentSessionId || event.properties?.sessionID || "",
            cwd: directory || process.cwd(),
          })
          try {
            await $`/opt/homebrew/bin/xh _memory-hook session-end ${payload} --agent opencode`
          } catch {}
          break
        }
      }
    },
  }
}
