// Xhawk session tracking plugin for OpenCode
// Auto-generated by xhawk (xh init)
// Do not edit manually — changes will be overwritten on the next xh init.
// Requires Bun runtime (used by OpenCode's plugin system for loading ESM plugins).
import type { Plugin } from "@opencode-ai/plugin"

export const XhawkPlugin: Plugin = async ({ directory }) => {
  const XH_CMD = "/opt/homebrew/bin/xh"
  let currentSessionID: string | null = null

  /**
   * Synchronous hook call via Bun.spawnSync.
   * Used for session-start and session-end events because:
   *  - session-start: ensures the session is registered before any tool calls
   *  - session-end:   opencode run exits on the same event that triggers this,
   *                   so async calls would be killed before completing
   */
  function callHookSync(args: string[], payload: Record<string, unknown>): void {
    try {
      const json = JSON.stringify(payload)
      Bun.spawnSync([XH_CMD, "_memory-hook", ...args], {
        cwd: directory,
        stdin: new TextEncoder().encode(json + "\n"),
        stdout: "ignore",
        stderr: "ignore",
      })
    } catch {
      // Silently ignore — plugin failures must not crash OpenCode
    }
  }

  return {
    event: async ({ event }) => {
      switch (event.type) {
        case "session.created": {
          const session = (event as any).properties?.info
          if (!session?.id) break
          currentSessionID = session.id
          callHookSync(["session-start", "--agent", "opencode"], {
            session_id: session.id,
            cwd: directory,
          })
          break
        }

        case "session.deleted": {
          // Fires on explicit session deletion in TUI (not on quit)
          const session = (event as any).properties?.info
          if (!session?.id) break
          currentSessionID = null
          callHookSync(["stop", "--agent", "opencode"], {
            session_id: session.id,
            cwd: directory,
          })
          break
        }

        case "server.instance.disposed": {
          // Fires when OpenCode shuts down (TUI close or opencode run exit).
          // session.deleted only fires on explicit user deletion, not on quit.
          if (!currentSessionID) break
          const sessionID = currentSessionID
          currentSessionID = null
          callHookSync(["stop", "--agent", "opencode"], {
            session_id: sessionID,
            cwd: directory,
          })
          break
        }
      }
    },
  }
}
